# vim: ft=dockerfile:
from alpine

run mkdir /app
workdir /app

run apk update && \
    apk add --no-cache build-base \
                       git \
                       jpeg-dev \
                       libxslt-dev \
                       mariadb-dev \
                       nodejs \
                       py-setuptools \
                       python2 \
                       python2-dev \
                       yarn \
                       zlib-dev

run ln -sf /usr/bin/python2.7 /usr/bin/python && \
    ln -sf /usr/bin/easy_install-2.7 /usr/bin/easy_install

run easy_install pip && \
    pip install --upgrade pip && \
    pip install virtualenv && \
    yarn global add gulp

run virtualenv .venv && \
    source .venv/bin/activate

copy package.json /app/
copy yarn.lock /app/
copy requirements/* /app/requirements/

run yarn install
run pip install -r requirements/dev-requirements.txt

copy . /app

run gulp build

run apk del build-base \
            git \
            nodejs \
            py-setuptools \
            python2-dev \
            yarn

add devops/entrypoint.sh /docker-entrypoint-initdb.d
