#!/bin/sh
yarn upgrade --latest
sed -ri'' 's/("material-components-web":) "\^[0-9]+\.[0-9]+\.[0-9]+"/\1 "^0.34.1"/' package.json
sed -ri'' 's/("rollup-plugin-commonjs":) "\^[0-9]+\.[0-9]+\.[0-9]+"/\1 "^8.4.1"/' package.json
sed -ri'' 's/("rollup-plugin-node-resolve":) "\^[0-9]+\.[0-9]+\.[0-9]+"/\1 "^4.2.4"/' package.json
yarn install
pip install -r requirements/requirements.txt --upgrade
