# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 14:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reputation", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="NQuestionsCriterion",
            fields=[
                (
                    "version",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        default="n_questions", editable=False, max_length=32
                    ),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Any number of answers up to and including this evaluates to 0.",
                        verbose_name="Number floor",
                    ),
                ),
                (
                    "ceiling",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Any number of answers from and including this evaluates to 1. If set to 0, no ceiling is set.",
                        verbose_name="Number ceiling",
                    ),
                ),
                (
                    "growth_rate",
                    models.FloatField(
                        default=0.01,
                        help_text="Steepness of the slope.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0)
                        ],
                    ),
                ),
                (
                    "for_reputation_types",
                    models.ManyToManyField(to="reputation.ReputationType"),
                ),
            ],
            options={"abstract": False},
        )
    ]
