# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 18:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reputation", "0003_auto_20190522_1817")]

    operations = [
        migrations.AddField(
            model_name="nanswerscriterion",
            name="badge_threshold",
            field=models.FloatField(
                default=0,
                help_text="Threshold for the badge to be awarded. If 0, is ignored.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="nquestionscriterion",
            name="badge_threshold",
            field=models.FloatField(
                default=0,
                help_text="Threshold for the badge to be awarded. If 0, is ignored.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
