# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 19:25
from __future__ import unicode_literals

import dalite.models.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reputation", "0004_auto_20190731_1914")]

    operations = [
        migrations.AlterField(
            model_name="nanswerscriterion",
            name="thresholds",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                default="",
                help_text="Thresholds for number of point change. If empty, all criterion points will give the same number of points. If one less than `Points per threshold`, the last point number goes to infinity. If it's the same length, the last number indicates the threshold after which points aren't gained.",
                verbose_name="Thresholds",
            ),
        ),
        migrations.AlterField(
            model_name="nquestionscriterion",
            name="thresholds",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                default="",
                help_text="Thresholds for number of point change. If empty, all criterion points will give the same number of points. If one less than `Points per threshold`, the last point number goes to infinity. If it's the same length, the last number indicates the threshold after which points aren't gained.",
                verbose_name="Thresholds",
            ),
        ),
    ]
