# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0005_auto_20190627_1441"),
        ("reputation", "0005_auto_20190731_1925"),
    ]

    operations = []
