# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0009_studentrationaleevaluationcriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrationaleevaluationcriterion',
            name='score_0',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='studentrationaleevaluationcriterion',
            name='score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentrationaleevaluationcriterion',
            name='score_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentrationaleevaluationcriterion',
            name='score_3',
            field=models.IntegerField(default=1),
        ),
    ]
