# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 14:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0009_rationaleevaluationcriterion'),
        ('reputation', '0009_questionlikedcriterion'),
        ('reputation', '0009_studentrationaleevaluationcriterion'),
    ]

    operations = [
    ]
