# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0011_auto_20190827_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationtype',
            name='model_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
