# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-03 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0012_reputationtype_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonrationalechoicescriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
        migrations.AddField(
            model_name='convincingrationalescriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
        migrations.AddField(
            model_name='nanswerscriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
        migrations.AddField(
            model_name='nquestionscriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
        migrations.AddField(
            model_name='questionlikedcriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
        migrations.AddField(
            model_name='rationaleevaluationcriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
        migrations.AddField(
            model_name='studentrationaleevaluationcriterion',
            name='badge_icon',
            field=models.CharField(default='donut_small', max_length=32),
        ),
    ]
