DATA_INVENTORY = [
    {
        "semester": "Fall2018",
        "courses": [
            {
                "teacher": "sahirbhatnagar",
                "discipline": "Statistics",
                "name": "EPIB607_Fall2018",
                "title": "EPIB607_Fall2018",
                "N_students": 92,
                "N_questions": 55,
                "N_answers": 4482,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM 324 2018",
                "title": "CHEM 324 Fall 2018",
                "N_students": 72,
                "N_questions": 62,
                "N_answers": 2173,
            },
            # {
            #     "teacher": "cleung",
            #     "discipline": "Chemistry",
            #     "name": "13022",
            #     "title": "General Chemistry F2018 Sec 17 & 18",
            #     "N_students": 24,
            #     "N_questions": 198,
            #     "N_answers": 1454,
            # },
            # {
            #     "teacher": "mrhachey",
            #     "discipline": "Chemistry",
            #     "name": "13004",
            #     "title": "General Chemistry",
            #     "N_students": 38,
            #     "N_questions": 149,
            #     "N_answers": 2515,
            # },
        ],
    },
    {
        "semester": "Winter2019",
        "courses": [
            {
                "teacher": "mrhachey",
                "discipline": "Chemistry",
                "name": "853",
                "title": "General Chemistry (202NYA05 - Winter 2019)",
                "N_students": 47,
                "N_questions": 67,
                "N_answers": 1823,
            },
            {
                "teacher": "Alice",
                "discipline": "Chemistry",
                "name": "FDSC230winter2019",
                "title": "FDSC230winter2019",
                "N_students": 38,
                "N_questions": 121,
                "N_answers": 910,
            },
            {
                "teacher": "McGillBIOL202",
                "discipline": "Biology",
                "name": "BIOL202PracticeInventory",
                "title": "BIOL202PracticeInventory",
                "N_students": 414,
                "N_questions": 204,
                "N_answers": 16680,
            },
            {
                "teacher": "McGillBIOL202",
                "discipline": "Biology",
                "name": "BIOL202TAConference",
                "title": "BIOL202TAConference",
                "N_students": 293,
                "N_questions": 40,
                "N_answers": 2973,
            },
            {
                "teacher": "provotas",
                "discipline": "Physics",
                "name": "PHYS102_2019",
                "title": "PHYS102_2019",
                "N_students": 641,
                "N_questions": 59,
                "N_answers": 33651,
            },
            {
                "teacher": "cpayne",
                "discipline": "English",
                "name": "Themes Winter 2019",
                "title": "Petrocultures and the Posthuman - Sections 4 & 5",
                "N_students": 44,
                "N_questions": 166,
                "N_answers": 279,
            },
            {
                "teacher": "adamsr",
                "discipline": "Physics",
                "name": "Waves (NYC) - RAdams - winter 2019",
                "title": "Waves (NYC) - RAdams - winter 2019",
                "N_students": 37,
                "N_questions": 27,
                "N_answers": 757,
            },
            {
                "teacher": "MegEm",
                "discipline": "Chemistry",
                "name": "NYA Winter 2019 Day",
                "title": "NYA Winter 2019 Day",
                "N_students": 15,
                "N_questions": 234,
                "N_answers": 573,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM 324 Winter 2019",
                "title": "CHEM 324 Winter 2019",
                "N_students": 46,
                "N_questions": 54,
                "N_answers": 1297,
            },
            {
                "teacher": "malessi",
                "discipline": "Chemistry",
                "name": "Winter2019",
                "title": "Winter2019",
                "N_students": 42,
                "N_questions": 24,
                "N_answers": 598,
            },
            {
                "teacher": "Alice",
                "discipline": "Chemistry",
                "name": "FDSC230winter2019",
                "title": "FDSC230winter2019",
                "N_students": 38,
                "N_questions": 121,
                "N_answers": 910,
            },
            {
                "teacher": "ccormier",
                "discipline": "Chemistry",
                "name": "ChimieGenerale_H2019",
                "title": "ChimieGenerale_H2019",
                "N_students": 20,
                "N_questions": 10,
                "N_answers": 76,
            },
            {
                "teacher": "michal",
                "discipline": "Chemistry",
                "name": "W2019_NYA",
                "title": "W2019_NYA",
                "N_students": 36,
                "N_questions": 16,
                "N_answers": 485,
            },
            {
                "teacher": "etempleton",
                "discipline": "Chemistry",
                "name": "ETNYA W2019",
                "title": "ETNYA W2019",
                "N_students": 22,
                "N_questions": 71,
                "N_answers": 937,
            },
        ],
    },
    {
        "semester": "Fall2019",
        "courses": [
            {
                "teacher": "mrhachey",
                "discipline": "Chemistry",
                "name": "18237",
                "title": "Fall 2019 - General Chemistry",
                "N_students": 39,
                "N_questions": 109,
                "N_answers": 2386,
            },
            {
                "teacher": "cleung",
                "discipline": "Chemistry",
                "name": "12765",
                "title": "General Chemistry F2019 Sec 29",
                "N_students": 15,
                "N_questions": 107,
                "N_answers": 502,
            },
            {
                "teacher": "hnadeau",
                "discipline": "Physics",
                "name": "Mechanics Fall 2019",
                "title": "NYA_F19",
                "N_students": 26,
                "N_questions": 35,
                "N_answers": 468,
            },
            {
                "teacher": "adamsr",
                "discipline": "Physics",
                "name": "NYA Mechanics - RAdams fall 2019",
                "title": "NYA Mechanics - RAdams fall 2019",
                "N_students": 32,
                "N_questions": 53,
                "N_answers": 1328,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM 324 Fall 2019",
                "title": "CHEM 324 Fall 2019",
                "N_students": 42,
                "N_questions": 110,
                "N_answers": 1328,
            },
            {
                "teacher": "sahirbhatnagar",
                "discipline": "Statistics",
                "name": "EPIB607_Fall2019",
                "title": "EPIB607_Fall2019",
                "N_students": 80,
                "N_questions": 40,
                "N_answers": 2909,
            },
            {
                "teacher": "NickPark",
                "discipline": "Unknown",
                "name": "Fall2019",
                "title": "Mechanics",
                "N_students": 35,
                "N_questions": 94,
                "N_answers": 1599,
            },
            {
                "teacher": "jfbriere",
                "discipline": "Physics",
                "name": "JFBriereNYAF19s01",
                "title": "Mechanics JFBriere Fall 2019 section 01",
                "N_students": 35,
                "N_questions": 44,
                "N_answers": 847,
            },
            {
                "teacher": "jfbriere",
                "discipline": "Physics",
                "name": "NYAJFBriereF19s05",
                "title": "Mechanics section 05 JFBriere Fall 2019",
                "N_students": 32,
                "N_questions": 44,
                "N_answers": 609,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM_205_Fall_2019",
                "title": "CHEM_205_Fall_2019",
                "N_students": 72,
                "N_questions": 129,
                "N_answers": 1718,
            },
            {
                "teacher": "guillermosanchezgr",
                "discipline": "Physics",
                "name": "Física Básica UANL",
                "title": "Grupo de FIBAS",
                "N_students": 192,
                "N_questions": 10,
                "N_answers": 1603,
            },
        ],
    },
    {
        "semester": "Winter2020",
        "courses": [
            {
                "teacher": "provotas",
                "discipline": "Physics",
                "name": "PHYS102_2020",
                "title": "PHYS102_2020",
                "N_students": 479,
                "N_questions": 16,
                "N_answers": 4943,
            },
            {
                "teacher": "BIOL112Instructor",
                "discipline": "Biology",
                "name": "BIOL112 2020",
                "title": "BIOL112 2020",
                "N_students": 96,
                "N_questions": 35,
                "N_answers": 133,
            },
            {
                "teacher": "McGillBIOL202",
                "discipline": "Physics",
                "name": "BIOL202_W2020",
                "title": "BIOL202_W2020",
                "N_students": 375,
                "N_questions": 111,
                "N_answers": 8674,
            },
            {
                "teacher": "chloegarzon",
                "discipline": "Chemistry",
                "name": "FDSC230Winter2020",
                "title": "FDSC230Winter2020",
                "N_students": 82,
                "N_questions": 12,
                "N_answers": 602,
            },
            {
                "teacher": "michal",
                "discipline": "Chemistry",
                "name": "1160",
                "title": "Organic Chemistry I (202DCP05 - Winter 2020)",
                "N_students": 22,
                "N_questions": 75,
                "N_answers": 255,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM_222_Winter_2020",
                "title": "CHEM_222_Winter_2020",
                "N_students": 45,
                "N_questions": 49,
                "N_answers": 1431,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM_324_Winter_2020",
                "title": "CHEM_324_Winter_2020",
                "N_students": 10,
                "N_questions": 54,
                "N_answers": 5,
            },
            {
                "teacher": "srobidoux",
                "discipline": "Chemistry",
                "name": "CHEM_205_Winter_2020",
                "title": "CHEM_205_Winter_2020",
                "N_students": 64,
                "N_questions": 8,
                "N_answers": 162,
            },
        ],
    },
]
