# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0059_remove_studentnotification_hover_text")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional. Select categories for this question. "
                "You can select multiple categories.",
                related_name="Categories",
                to="peerinst.Category",
            ),
        )
    ]
