# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 19:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0064_auto_20190219_1934")]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="datetime_second",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="datetime_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
