# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 05:12


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peerinst", "0064_auto_20190217_0359"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastLogout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_logout", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional. Select categories for this question. You can select multiple categories.",  # noqa
                related_name="Categories",
                to="peerinst.Category",
            ),
        ),
    ]
