# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("peerinst", "0066_auto_20190219_1622"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachernotification",
            unique_together=set(
                [("teacher", "notification_type", "object_id")]
            ),
        )
    ]
