# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 17:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0065_auto_20190219_1934"),
        ("peerinst", "0067_auto_20190219_1716"),
    ]

    operations = []
