# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0070_answer_datetime_fix")]

    operations = [
        migrations.AlterField(
            model_name="answerannotation",
            name="score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "0-Never Show"),
                    (1, "1-Not Convincing"),
                    (2, "2-Somewhat Convincing"),
                    (3, "3-Very Convincing"),
                ],
                default=None,
                null=True,
            ),
        )
    ]
