# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0071_auto_20190227_1504"),
        ("peerinst", "0071_question_second_answer_needed"),
    ]

    operations = []
