# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0071_auto_20190227_1504"),
        ("peerinst", "0071_rationale_only_answer_fix"),
    ]

    operations = []
