# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 16:02
from __future__ import unicode_literals

from django.db import migrations


def add_second_choice_needed_false_to_rationale_only(apps, _):
    Question = apps.get_model("peerinst", "Question")

    for question in Question.objects.filter(type="RO"):
        question.second_answer_needed = False
        question.save()


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0072_merge_20190227_1617")]

    operations = [
        migrations.RunPython(add_second_choice_needed_false_to_rationale_only)
    ]
