# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0001_initial"),
        ("peerinst", "0073_question_second_answer_needed_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroupassignment",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quality.Quality",
            ),
        )
    ]
