# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0074_studentgroupassignment_quality"),
        ("peerinst", "0074_auto_20190310_0251"),
    ]

    operations = []
