# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 19:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0003_auto_20190314_1938"),
        ("peerinst", "0075_merge_20190311_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="checked_by_quality",
            field=models.ForeignKey(
                blank=True,
                help_text="Which quality was used to check if rationale "
                "is accepted",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checking_quality",
                to="quality.Quality",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="filtered_with_quality",
            field=models.ForeignKey(
                blank=True,
                help_text="Chich quality was used to filter shown rationales.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filtering_quality",
                to="quality.Quality",
            ),
        ),
    ]
