# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "__first__"),
        ("peerinst", "0075_questionflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="checked_by_quality",
            field=models.ForeignKey(
                blank=True,
                help_text="Which quality was used to check if rationale is accepted",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checking_quality",
                to="quality.Quality",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="filtered_with_quality",
            field=models.ForeignKey(
                blank=True,
                help_text="Chich quality was used to filter shown rationales.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filtering_quality",
                to="quality.Quality",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quality.Quality",
            ),
        ),
        migrations.AddField(
            model_name="studentgroupassignment",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quality.Quality",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quality.Quality",
            ),
        ),
    ]
