# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0075_questionflag"),
        ("peerinst", "0076_auto_20190319_1919"),
    ]

    operations = []
