# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0076_auto_20190323_1942")]

    operations = [
        migrations.AlterModelOptions(
            name="questionflag", options={"verbose_name": "flagged question"}
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quality.Quality",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroupassignment",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quality.Quality",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quality.Quality",
            ),
        ),
    ]
