# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 19:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0077_auto_20190326_1216"),
        ("peerinst", "0076_auto_20190402_1456"),
    ]

    operations = []
