# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0002_auto_20190320_1534"),
        ("peerinst", "0077_merge_20190319_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quality.Quality",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quality.Quality",
            ),
        ),
    ]
