# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0078_merge_20190402_1904"),
        ("peerinst", "0077_auto_20190410_0325"),
    ]

    operations = []
