# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0079_merge_20190410_1221")]

    operations = [
        migrations.RemoveField(
            model_name="question", name="rationale_selection_algorithm"
        )
    ]
