# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 19:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0079_merge_20190410_1221")]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. An image to include in collection thumbnail. Accepted formats: .jpg, .jpeg, .png, .gif",
                        null=True,
                        upload_to="images",
                        verbose_name="Thumbnail image",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, null=True),
                ),
                (
                    "assignments",
                    models.ManyToManyField(to="peerinst.Assignment"),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peerinst.Discipline",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to="peerinst.Teacher",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="peerinst.Teacher",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="studentgroupassignment",
            name="order",
            field=models.TextField(blank=True),
        ),
    ]
