# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0082_auto_20190526_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
