# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0082_auto_20190526_1938"),
        ("peerinst", "0081_teacher_last_page_access"),
    ]

    operations = []
