# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-26 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0083_collection_private"),
        ("peerinst", "0083_merge_20190610_1742"),
    ]

    operations = []
