# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0084_auto_20190731_1713")]

    operations = [
        migrations.RemoveField(model_name="teacher", name="last_page_access"),
        migrations.AddField(
            model_name="teacher",
            name="last_dashboard_access",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the teacher went on their teacher dashboard.",
                null=True,
            ),
        ),
    ]
