# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0084_merge_20190726_2104")]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="filtered_with_quality",
            field=models.ForeignKey(
                blank=True,
                help_text="Which quality was used to filter shown rationales.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filtering_quality",
                to="quality.Quality",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="assignments",
            field=models.ManyToManyField(blank=True, to="peerinst.Assignment"),
        ),
    ]
