# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0084_auto_20190716_1930")]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="collection",
            name="assignments",
            field=models.ManyToManyField(blank=True, to="peerinst.Assignment"),
        ),
        migrations.AlterField(
            model_name="runningtask",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="running_tasks",
                to="peerinst.Teacher",
            ),
        ),
    ]
