# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0085_auto_20190801_2034"),
        ("peerinst", "0084_auto_20190731_1713"),
    ]

    operations = []
