# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peerinst", "0085_auto_20190813_1406"),
        ("peerinst", "0085_auto_20190810_1400"),
    ]

    operations = []
