# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-23 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0086_auto_20190815_2150'),
        ('peerinst', '0086_auto_20190823_1338'),
    ]

    operations = [
    ]
