# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0087_auto_20190821_1332")]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="showing",
            field=models.BooleanField(default=True),
        )
    ]
