# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peerinst", "0088_usermessage_showing")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="peerinst.SaltiseMember"
            ),
        )
    ]
