# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0087_merge_20190823_2012'),
        ('peerinst', '0090_message_created_on'),
    ]

    operations = [
    ]
