# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import peerinst.models.question


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0091_merge_20190827_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. An image to include after the question text. Accepted formats: .jpg, .jpeg, .png, .gif', null=True, upload_to=peerinst.models.question.images, verbose_name='Question image'),
        ),
    ]
