# Generated by Django 2.2.14 on 2020-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0095_newuserrequest_userurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestions',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
