# Generated by Django 2.2.14 on 2020-07-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0096_assignmentquestions_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentquestions',
            options={'ordering': ['rank']},
        ),
    ]
