# Generated by Django 2.2.14 on 2020-07-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0097_auto_20200714_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentquestions',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peerinst.Assignment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional. A video or simulation to include after the question text. All videos should include transcripts.  Only videos from youtube (i.e. https://www.youtube.com/embed/...) and simulations from phet (i.e. https://phet.colorado.edu/sims/html/...) are currently supported.', verbose_name='Question video URL'),
        ),
    ]
