# Generated by Django 2.2.14 on 2020-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0100_auto_20200731_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='conclusion_page',
            field=models.TextField(blank=True, help_text='Any notes you would like to leave for students\n            to read that will be shown after the last question of the assignment.\n            ', null=True, verbose_name='Post Assignment Notes'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, help_text='Notes you would like keep for yourself\n            (or other teachers) regarding this assignment\n            ', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='intro_page',
            field=models.TextField(blank=True, help_text='Any special instructions you would like\n            students to read before they start the assignment.\n            ', null=True, verbose_name='Assignment Cover Page'),
        ),
    ]
