# Generated by Django 2.2.14 on 2020-08-07 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peerinst', '0101_auto_20200731_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='conclusion_page',
            field=models.TextField(blank=True, help_text='Any notes you would like to leave for students\n            to read that will be shown after the last\n            question of the assignment.\n            ', null=True, verbose_name='Post Assignment Notes'),
        ),
        migrations.AlterUniqueTogether(
            name='answerannotation',
            unique_together={('answer', 'annotator')},
        ),
    ]
