# Generated by Django 2.2.14 on 2020-08-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerinst', '0102_auto_20200807_0346'),
        ('peerinst', '0102_auto_20200807_0403'),
    ]

    operations = [
    ]
