# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MinWordsCriterion",
            fields=[
                (
                    "version",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        default="min_words", editable=False, max_length=32
                    ),
                ),
                ("min_words", models.PositiveIntegerField(unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Quality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="UsesCriterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("version", models.PositiveIntegerField()),
                ("use_latest", models.BooleanField()),
                ("weight", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="quality",
            name="criterions",
            field=models.ManyToManyField(to="quality.UsesCriterion"),
        ),
    ]
