# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 20:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="mincharscriterion",
            name="binary_threshold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minwordscriterion",
            name="binary_threshold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="negwordscriterion",
            name="binary_threshold",
            field=models.BooleanField(default=False),
        ),
    ]
