# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("quality", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="RejectedAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "reasons",
                    models.TextField(
                        help_text="json string containing info about criterions used to reject the rationale"
                    ),
                ),
                (
                    "quality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quality.Quality",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mincharscriterionrules",
            name="threshold",
            field=models.FloatField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="minwordscriterionrules",
            name="threshold",
            field=models.FloatField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
    ]
