# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="mincharscriterionrules",
            name="min_chars",
            field=models.PositiveIntegerField(verbose_name="Min characters"),
        ),
        migrations.AlterField(
            model_name="minwordscriterionrules",
            name="min_words",
            field=models.PositiveIntegerField(verbose_name="Min words"),
        ),
    ]
