# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MinCharsCriterion",
            fields=[
                (
                    "version",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        default="min_chars", editable=False, max_length=32
                    ),
                ),
                ("min_chars", models.PositiveIntegerField(unique=True)),
            ],
            options={"abstract": False},
        )
    ]
