# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="minwordscriterion",
            name="min_words",
            field=models.PositiveIntegerField(unique=True),
        )
    ]
