# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 16:38
from __future__ import unicode_literals

from django.db import migrations
import quality.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [("quality", "0002_auto_20190320_1534")]

    operations = [
        migrations.AlterField(
            model_name="mincharscriterionrules",
            name="threshold",
            field=quality.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="minwordscriterionrules",
            name="threshold",
            field=quality.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
    ]
