# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0002_auto_20190311_1819")]

    operations = [
        migrations.AlterField(
            model_name="mincharscriterion",
            name="uses_rules",
            field=models.TextField(
                blank=True,
                help_text="Comma separated list of used rules for the "
                "criterion found as the fields of the associated rules "
                "object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="mincharscriterionrules",
            name="min_chars",
            field=models.PositiveIntegerField(
                help_text="The minimum number of characters needed by a "
                "rationale.",
                verbose_name="Min characters",
            ),
        ),
        migrations.AlterField(
            model_name="minwordscriterion",
            name="uses_rules",
            field=models.TextField(
                blank=True,
                help_text="Comma separated list of used rules for the "
                "criterion found as the fields of the associated rules "
                "object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="minwordscriterionrules",
            name="min_words",
            field=models.PositiveIntegerField(
                help_text="The minimum number of words needed by a "
                "rationale.",
                verbose_name="Min words",
            ),
        ),
    ]
