# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models

import dalite.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0004_rightanswercriterion_rightanswercriterionrules")
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedAnswerCriterion",
            fields=[
                (
                    "version",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "uses_rules",
                    dalite.models.custom_fields.CommaSepField(
                        blank=True,
                        help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",  # noqa
                    ),
                ),
                ("is_beta", models.BooleanField(default=False)),
                ("binary_threshold", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default="selected_answer",
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "for_quality_types",
                    models.ManyToManyField(to="quality.QualityType"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SelectedAnswerCriterionRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold",
                    dalite.models.custom_fields.ProbabilityField(
                        help_text="Minimum value for the answer to be accepted",  # noqa
                        verbose_name="Threshold",
                    ),
                ),
                (
                    "default_if_never_shown",
                    dalite.models.custom_fields.ProbabilityField(
                        help_text="Value to evaluate to if answer never shown before.",  # noqa
                        verbose_name="Default value if never shown",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
