# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import dalite.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "quality",
            "0005_selectedanswercriterion_selectedanswercriterionrules",
        )
    ]

    operations = [
        migrations.CreateModel(
            name="LikelihoodCriterion",
            fields=[
                (
                    "version",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "uses_rules",
                    dalite.models.custom_fields.CommaSepField(
                        blank=True,
                        help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
                    ),
                ),
                ("is_beta", models.BooleanField(default=False)),
                ("binary_threshold", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default="likelihood", editable=False, max_length=32
                    ),
                ),
                (
                    "for_quality_types",
                    models.ManyToManyField(to="quality.QualityType"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LikelihoodCriterionRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold",
                    dalite.models.custom_fields.ProbabilityField(
                        help_text="Minimum value for the answer to be accepted",
                        verbose_name="Threshold",
                    ),
                ),
                (
                    "languages",
                    dalite.models.custom_fields.CommaSepField(
                        blank=True,
                        help_text="Accepted languages. Choices are english and french.",
                        null=True,
                        verbose_name="Languages",
                    ),
                ),
                (
                    "max_gram",
                    models.PositiveIntegerField(
                        help_text="The maximum size of n-gram to use.",
                        verbose_name="Max gram",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
