# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dalite.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [("quality", "0007_auto_20190424_1656")]

    operations = [
        migrations.CreateModel(
            name="LikelihoodCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.PositiveIntegerField()),
                ("hash", models.CharField(db_index=True, max_length=32)),
                ("likelihood", dalite.models.custom_fields.ProbabilityField()),
                (
                    "likelihood_random",
                    dalite.models.custom_fields.ProbabilityField(),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quality.LikelihoodLanguage",
                    ),
                ),
            ],
        )
    ]
