# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quality.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [("quality", "0007_auto_20190424_1656")]

    operations = [
        migrations.CreateModel(
            name="LikelihoodCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=32)),
                (
                    "likelihood",
                    quality.models.custom_fields.ProbabilityField(),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quality.LikelihoodCriterion",
                    ),
                ),
                (
                    "rules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quality.LikelihoodCriterionRules",
                    ),
                ),
            ],
        )
    ]
