# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0008_likelihoodcache")]

    operations = [
        migrations.AlterField(
            model_name="likelihoodcache",
            name="hash",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        )
    ]
