# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 18:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality", "0008_likelihoodcache")]

    operations = [
        migrations.AlterField(
            model_name="likelihoodcache",
            name="answer",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
