# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 18:42
from __future__ import unicode_literals

import dalite.models.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quality", "0012_qualitycache")]

    operations = [
        migrations.AlterField(
            model_name="likelihoodcache",
            name="likelihood",
            field=dalite.models.custom_fields.ProbabilityField(),
        ),
        migrations.AlterField(
            model_name="likelihoodcache",
            name="likelihood_random",
            field=dalite.models.custom_fields.ProbabilityField(),
        ),
        migrations.AlterField(
            model_name="likelihoodcriterion",
            name="uses_rules",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="likelihoodcriterionrules",
            name="threshold",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="likelihoodlanguage",
            name="n_gram_urls",
            field=dalite.models.custom_fields.CommaSepField(),
        ),
        migrations.AlterField(
            model_name="mincharscriterion",
            name="uses_rules",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="mincharscriterionrules",
            name="threshold",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="minwordscriterion",
            name="uses_rules",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="minwordscriterionrules",
            name="threshold",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="negwordscriterion",
            name="uses_rules",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="negwordscriterionrules",
            name="neg_words",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Words considered to be negative.",
                null=True,
                verbose_name="Negative words",
            ),
        ),
        migrations.AlterField(
            model_name="negwordscriterionrules",
            name="threshold",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="rightanswercriterion",
            name="uses_rules",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="rightanswercriterionrules",
            name="threshold",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="selectedanswercriterion",
            name="uses_rules",
            field=dalite.models.custom_fields.CommaSepField(
                blank=True,
                help_text="Comma separated list of used rules for the criterion found as the fields of the associated rules object. Make sure to use the verbose_name",
            ),
        ),
        migrations.AlterField(
            model_name="selectedanswercriterionrules",
            name="default_if_never_shown",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Value to evaluate to if answer never shown before.",
                verbose_name="Default value if never shown",
            ),
        ),
        migrations.AlterField(
            model_name="selectedanswercriterionrules",
            name="threshold",
            field=dalite.models.custom_fields.ProbabilityField(
                help_text="Minimum value for the answer to be accepted",
                verbose_name="Threshold",
            ),
        ),
    ]
